#!/bin/bash
# PreToolUse hook: enforce workspace isolation for ARSD roles.
# Supports two modes via isolation.conf:
#   - blacklist (default): lines are blocked directory prefixes
#   - whitelist: first line is MODE=whitelist, remaining lines are allowed prefixes
# Exit 0 = allow, Exit 2 = block (Claude Code convention).
#
# Generated by agent-platform setup_project. Do not edit manually.

source "$(dirname "$0")/hook-log.sh"

CONF_FILE="$(dirname "$0")/isolation.conf"
if [[ ! -f "$CONF_FILE" ]]; then
    exit 0  # no config = no restrictions
fi

input=$(cat)

# Detect mode: whitelist or blacklist
MODE="blacklist"
if grep -q '^MODE=whitelist' "$CONF_FILE"; then
    MODE="whitelist"
fi

# Read directory prefixes from config (skip comments, empty lines, MODE= lines)
mapfile -t DIRS < <(grep -v '^#' "$CONF_FILE" | grep -v '^$' | grep -v '^MODE=')

if [[ ${#DIRS[@]} -eq 0 ]]; then
    exit 0
fi

# Extract paths from the JSON tool input
paths=$(echo "$input" | grep -oP '"(/home/[^"]+|~/[^"]+)' | sed 's/^"//' | head -30)

if [[ -z "$paths" ]]; then
    exit 0
fi

for path in $paths; do
    # Expand ~ to home directory
    expanded="${path/#\~/$HOME}"

    # Always allow system-level directories all roles need
    if [[ "$expanded" == "$HOME/.claude" || "$expanded" == "$HOME/.claude/"* \
       || "$expanded" == "$HOME/engineering-knowledge" || "$expanded" == "$HOME/engineering-knowledge/"* \
       || "$expanded" == "/tmp" || "$expanded" == "/tmp/"* ]]; then
        continue
    fi

    if [[ "$MODE" == "blacklist" ]]; then
        for blocked in "${DIRS[@]}"; do
            blocked_expanded="${blocked/#\~/$HOME}"
            if [[ "$expanded" == "$blocked_expanded" || "$expanded" == "$blocked_expanded"/* ]]; then
                hook_log "isolation" "BLOCK" "$expanded"
                echo "BLOCKED: 当前角色禁止访问 $expanded（工作空间隔离策略）。"
                echo "如需该目录的信息，请用 send-to 命令请求对应角色提供。例如：send-to coordinator \"请提供 xxx 的信息\""
                exit 2
            fi
        done
    else
        # Whitelist mode: path must match at least one allowed prefix
        allowed=false
        for allow in "${DIRS[@]}"; do
            allow_expanded="${allow/#\~/$HOME}"
            if [[ "$expanded" == "$allow_expanded" || "$expanded" == "$allow_expanded"/* ]]; then
                allowed=true
                break
            fi
        done
        if [[ "$allowed" == false ]]; then
            hook_log "isolation" "BLOCK" "$expanded (whitelist)"
            echo "BLOCKED: 当前角色只能访问自己的工作空间和共享空间，禁止访问 $expanded。"
            echo "如需其他目录的信息，请用 send-to 命令请求对应角色提供。例如：send-to dev \"请提供 xxx 的信息\""
            exit 2
        fi
    fi
done

hook_log "isolation" "PASS"
exit 0
