#!/bin/bash
# PreToolUse hook: enforce workspace isolation for ARSD roles.
# Reads BLOCKED_DIRS from the companion .conf file (one path per line).
# Exit 0 = allow, Exit 2 = block (Claude Code convention).
#
# Generated by agent-platform setup_project. Do not edit manually.

CONF_FILE="$(dirname "$0")/isolation.conf"
if [[ ! -f "$CONF_FILE" ]]; then
    exit 0  # no config = no restrictions
fi

input=$(cat)

# Read blocked directory prefixes from config
mapfile -t BLOCKED < <(grep -v '^#' "$CONF_FILE" | grep -v '^$')

if [[ ${#BLOCKED[@]} -eq 0 ]]; then
    exit 0
fi

# Extract paths from the JSON tool input
paths=$(echo "$input" | grep -oP '"(/home/[^"]+|~/[^"]+)' | sed 's/^"//' | head -30)

for path in $paths; do
    # Expand ~ to home directory
    expanded="${path/#\~/$HOME}"

    for blocked in "${BLOCKED[@]}"; do
        blocked_expanded="${blocked/#\~/$HOME}"
        # Check if path starts with blocked prefix
        if [[ "$expanded" == "$blocked_expanded" || "$expanded" == "$blocked_expanded"/* ]]; then
            echo "BLOCKED: 当前角色禁止访问 $expanded（工作空间隔离策略）。"
            echo "如需该目录的信息，请用 send-to 命令请求对应角色提供。例如：send-to coordinator \"请提供 xxx 的信息\""
            exit 2
        fi
    done
done

exit 0
