#!/bin/bash
# Shared logging helper for all hooks.
# Usage: source hook-log.sh; hook_log "hook-name" "RESULT" "optional detail"
#
# Log file: same directory as hook scripts → .claude/hooks/hook.log
# Format: ISO_TIME HOOK_NAME RESULT DETAIL
# Generated by agent-platform. Do not edit manually.

_HOOK_LOG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
_HOOK_LOG_FILE="$_HOOK_LOG_DIR/hook.log"

hook_log() {
    local hook="$1" result="$2" detail="${3:-}"
    printf '%s %s %s %s\n' "$(date -Iseconds)" "$hook" "$result" "$detail" >> "$_HOOK_LOG_FILE" 2>/dev/null
}
