#!/bin/bash
# PreToolUse hook: Role Guardian — periodic role principle reminder.
# Injects role-specific reminders every N tool calls or M minutes
# to prevent role drift in long conversations.
#
# Reads pre-built JSON response from role-guardian-response.json.
# Generated by agent-platform setup_isolation.py. Do not edit manually.

RESPONSE_FILE="$(dirname "$0")/role-guardian-response.json"
if [[ ! -f "$RESPONSE_FILE" ]]; then
    exit 0
fi

INTERVAL=${ROLE_GUARDIAN_INTERVAL:-25}
TIME_INTERVAL=${ROLE_GUARDIAN_TIME:-600}  # 10 minutes in seconds

# Stable state file keyed by workspace path
WORKSPACE_DIR="$(cd "$(dirname "$0")/../.." 2>/dev/null && pwd)"
STATE_FILE="/tmp/.role-guardian-$(echo -n "$WORKSPACE_DIR" | md5sum | cut -c1-8)"

NOW=$(date +%s)

# Read state: count last_injection_time
if [[ -f "$STATE_FILE" ]]; then
    read -r COUNT LAST_TIME < "$STATE_FILE"
    [[ -z "$COUNT" ]] && COUNT=0
    [[ -z "$LAST_TIME" ]] && LAST_TIME=$NOW
else
    COUNT=0
    LAST_TIME=$NOW
fi

COUNT=$((COUNT + 1))
TIME_ELAPSED=$((NOW - LAST_TIME))

# Trigger if count hits interval OR time exceeds threshold
if [[ $((COUNT % INTERVAL)) -ne 0 ]] && [[ $TIME_ELAPSED -lt $TIME_INTERVAL ]]; then
    echo "$COUNT $LAST_TIME" > "$STATE_FILE"
    exit 0
fi

# Triggered — reset timer, inject reminder
echo "$COUNT $NOW" > "$STATE_FILE"
cat "$RESPONSE_FILE"
exit 0
